options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', 'main']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    [
      'gcloud', 'run', 'deploy', 'my-app',
      '--image', 'gcr.io/$PROJECT_ID/my-app',
      '--platform', 'managed',
      '--region', 'europe-west3',
      '--allow-unauthenticated'
    ]